### ISSUE TITLE
Perform a calculation to set a (new) state

### ISSUE THREAD

**Issue by NicoSomerwil** [pmazz/ps_hassio_entities#4]
Hi there,

I recently discovered your very helpful script to set states and/or attributes. So, thanks a lot!!

I'm looking for a way to use this (or customized) script) to do a simple calculation to set the new state. 
But, I'm an enthusiastic but not yet highly skilled HA user. ;-)

I have a sensor that counts the motions from a motion sensor:

sensor:
  - platform: history_stats
    name: Beweging Kidsroom
    entity_id: binary_sensor.kidsroom_motion_sensor
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
   end: '{{ now() }}'

But sometimes I have a fake count (in this case by restarting HA). 
So in that case I like to correct this by subtracting the value by 1 (from the state (string value)) .
So the new state should be the value of sensor.beweging_kidsroom minus 1

Is that possible with (some change/addition to) your script ?

I tried things like:

service: python_script.hass_entities
data:
  action: set_state
  entity_id: sensor.beweging_kidsroom
  state: {{ states.sensor.beweging_kidsroom.state | int -1 }}. # with and without quotes

But yet without luck. I also tried to replace the state by using another state (also with no luck)
..
state: {{ states.sensor.beweging_slaapkamer.state }}. # with and without quotes

Maybe you are willing to help me to solve my issue. Or maybe you have a tip or other idea how to solve it.

Thanks in advance for a reply.

Good luck!

Best Regards,

Nico

**Comment by pmazz** [comment]
Hi Nico,
I appreciate your kind words.

It sounds something related to how you set the state.
I also noticed a `.` between `}}` and `#`, which should not be there.

Would you try to change this
```
state: {{ states.sensor.beweging_kidsroom.state | int -1 }}. # with and without quotes
```
to this ?
``` 
state: "{{ (states('sensor.beweging_kidsroom') | int) -1 }}"
```

The [official documentation](https://www.home-assistant.io/docs/configuration/templating/#states) suggests to use `states('sensor.name')` instead of `states.sensor.name.state` to prevent strange behaviors when dealing with HA restart.

Let me know if that helps.

**Comment by NicoSomerwil** [comment]
Hi Paolo,

Thanks for your quick and friendly reply. Top!

I guess that the script can't handle this kind of 'statements'.
I was not yet able to change the value this way.

Perhaps I'm asking for something that could not be done (by me ;-)

Thanks anyway!

Good luck and all the best!

Best Regards,

Nico

**Comment by pmazz** [comment]
I'm sorry Nico, don't give up ;-)

I somewhere use it in a very similar way, and it works...
```
- service: python_script.hass_entities
  data:
    action: set_state
    entity_id: sensor.paolo_home_from
    state: "{{ 'At home since '~ now().strftime('%H.%M') }}"
```

What problem do you get?
Did you try to enable the log? (check at bottom of [readme.md](https://github.com/pmazz/ps_hassio_entities/blob/master/README.md#logging))
